# name: Restart Airflow Containers

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'Dockerfile'
#       - 'docker-compose.yaml'
#       - 'requirements.txt'
#       - 'airflow.cfg'

# jobs:
#   restart_airflow:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 설정 수정시 SSH로 Airflow EC2 접속해 컨테이너 재시작
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.AIRFLOW_EC2_HOST }}
#           username: ${{ secrets.AIRFLOW_EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           script: |
#             cd /home/ubuntu/airflow-setup/local-executor-airflow # Airflow Project path
#             git pull origin $(git rev-parse --abbrev-ref HEAD) # 현재 브랜치에서 최신 코드 가져오기
#             docker compose down
#             docker compose build
#             docker compose up -d
